### ISSUE TITLE
error in pursuit_3 (line 83)

### ISSUE THREAD

**Issue by SweetPin** [wanghuohuo0716/hanting_based_on_voronoi#3]
Hello! When I run this code, it shows
错误错误使用  - 
矩阵维度必须一致。
出错 pursuit_3 (line 83)
            V_dist=sum(abs(V(i,:)-C_pos).^2,2).^(1/2);
How should I solve it?

**Comment by heguohao0728** [comment]
First of all, you must have MATLAB 2018a or other latest version.
If you have the right version of MATLAB:
Did you have this error each time you run the code? The cause of this error is still unknown, but when I run the code for 1000 times, this error will show only a few times (like 10-20). This code is just for proving our algorithm, so a little mistakes is acceptable. This is why  we choose to ignored this error.
If you find the cause of this error or have some methods to solve this, please tell us. We will appreciate your selfless dedication!

**Comment by SweetPin** [comment]
Thank you, it is because my matlab version is too old. When I change to MATLAB 2019a,this problem has not appeared yet.
