### ISSUE TITLE
3D simulation in the future

### ISSUE THREAD

**Issue by SweetPin** [wanghuohuo0716/hanting_based_on_voronoi#4]
The work you have done is perfect. Do you have plans for 3D simulation in the future? On the basis of this code, do we need a lot of changes?

**Comment by wanghuohuo0716** [comment]
sorry,we have no plan for 3D simulation in the future. I think there will be little change from 2D to 3D simulation, ,there may exist 3d voronoi funtion in matlab. Good luck~

**Comment by SweetPin** [comment]
Thank you for your reply!
