### ISSUE TITLE
索引超出矩阵维度。  出错 pursuit (line 83)             V_dist=sum(abs(V(i,:)-C_pos(i,:)).^2,2).^(1/2);

### ISSUE THREAD

**Issue by danghc-bit** [wanghuohuo0716/hanting_based_on_voronoi#5]
索引超出矩阵维度。

出错 pursuit (line 83)
            V_dist=sum(abs(V(i,:)-C_pos(i,:)).^2,2).^(1/2);

**Comment by wanghuohuo0716** [comment]
#3 这是一个已知的问题

**Comment by danghc-bit** [comment]
你好，这个方法我试了，还是相同的问题，关键是C_pos只有十二行而V的行数一直在变化，请问你运行成功了吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Yan Wang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月30日(星期四) 中午1:25
收件人:&nbsp;"wanghuohuo0716/hanting_based_on_voronoi"<hanting_based_on_voronoi@noreply.github.com&gt;;
抄送:&nbsp;"海🅥"<1158825391@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [wanghuohuo0716/hanting_based_on_voronoi] 索引超出矩阵维度。  出错 pursuit (line 83)             V_dist=sum(abs(V(i,:)-C_pos(i,:)).^2,2).^(1/2); (#5)





 
Closed #5.

**Comment by wanghuohuo0716** [comment]
是的，我可以运行成功，可能极特殊情况会有这种问题，我也不太确定？

**Comment by danghc-bit** [comment]
你可以把你的关于这个仿真的.m文件给我发一份吗，是不是github的有啥错误，




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Yan Wang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月7日(星期四) 上午10:57
收件人:&nbsp;"wanghuohuo0716/hanting_based_on_voronoi"<hanting_based_on_voronoi@noreply.github.com&gt;;
抄送:&nbsp;"海🅥"<1158825391@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [wanghuohuo0716/hanting_based_on_voronoi] 索引超出矩阵维度。  出错 pursuit (line 83)             V_dist=sum(abs(V(i,:)-C_pos(i,:)).^2,2).^(1/2); (#5)





 
是的，我可以运行成功，可能极特殊情况会有这种问题，我也不太确定？

**Comment by wanghuohuo0716** [comment]
[src.zip](https://github.com/wanghuohuo0716/hanting_based_on_voronoi/files/4596745/src.zip)

**Comment by danghc-bit** [comment]
谢谢&nbsp; 不过还是那个问题






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Yan Wang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月8日(星期五) 上午10:46
收件人:&nbsp;"wanghuohuo0716/hanting_based_on_voronoi"<hanting_based_on_voronoi@noreply.github.com&gt;;
抄送:&nbsp;"海🅥"<1158825391@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [wanghuohuo0716/hanting_based_on_voronoi] 索引超出矩阵维度。  出错 pursuit (line 83)             V_dist=sum(abs(V(i,:)-C_pos(i,:)).^2,2).^(1/2); (#5)





 
src.zip
